---
deployment:
  tasks:
    - export DEPLOYPATH=/home/bharatvz/public_html/
    - /bin/rm -Rf $DEPLOYPATH
    - /bin/mkdir $DEPLOYPATH
    - /bin/cp build/* -R $DEPLOYPATH
    - /bin/cp build/.env -R $DEPLOYPATH
    - /bin/cp build/.htaccess -R $DEPLOYPATH
    - /bin/cp build/services/application/.htaccess $DEPLOYPATH/services/application/
