---
deployment:
  tasks:
    - export DEPLOYPATH=/home/bharatvz/public_html/
    - /bin/rm -Rf $DEPLOYPATH
    - /bin/mkdir $DEPLOYPATH
    - /bin/cp build/* -R $DEPLOYPATH
    - /bin/cp build/.* -R $DEPLOYPATH
