---
deployment:
  tasks:
    - export DEPLOYPATH=/home4/bharabgn/public_html/
    - /bin/rm -Rf $DEPLOYPATH
    - /bin/mkdir $DEPLOYPATH
    - /bin/cp build/* -R $DEPLOYPATH
    - /bin/cp build/.htaccess -R $DEPLOYPATH