const configPanel = [
  {
    type: 'text',
    field: 'user_name',
    placeHolder: 'Ex: John',
    defaultValue: '',
    maxLength: 25,
    mandatories: {
      required: true,
      validationRule: 'minOne',
    },
    className: '',
    isHelp: {},
  },
];

const masterConfig = [
  {
    id: 'config_id',
    index: 'config_id',
    elementType: 'hidden',
    value: '',
    className: '',
  },
  {
    id: 'web',
    index: 'web',
    label: 'Website',
    elementType: 'text',
    value: '',
    placeHolder: 'JohnDoe.com',
    className: 'col-md-4 col-sm-6',
    options: {
      required: true,
      validation: /([^\s])/,
      errorMsg: 'Enter a valid website',
      help: [
        `Your web domain`,
        `This value will be set to your global variables, which can be accessed accross application`,
      ],
    },
  },
  {
    id: 'email',
    index: 'email',
    label: 'Email',
    elementType: 'text',
    value: '',
    placeHolder: 'support@JohnDoe.com',
    className: 'col-md-4 col-sm-6',
    options: {
      required: true,
      validation: /^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,5})+$/,
      errorMsg: 'Enter a valid email',
      help: [
        `Your personal or company mail id, which will be exposed to public.`,
        `This value will be set to your global variables, which can be accessed accross application`,
      ],
    },
  },
  {
    id: 'google_login_auth_token',
    index: 'google_login_auth_token',
    label: 'Google Login Auth Token',
    elementType: 'textArea',
    value: '',
    placeHolder: 'xxYYzz',
    className: 'col-md-4 col-sm-6',
    options: {
      required: true,
      rowLength: '100',
      validation: /([^\s])/,
      errorMsg: 'Auth token required',
      help: [
        `How to get them?`,
        `Go to https://console.cloud.google.com/`,
        `Click API Services`,
        `Click Credentials`,
        `Click +Create Credentials at the top center`,
        `Click Oauth Client Id`,
        `Select Web Application, give a suitable name`,
        `Click Add URI and type your domain URL.`,
        `Click Create`,
        `Copy Client ID`,
        `Paste here.`,
        `You're done.`,
        `Now you allow public to login via google login`,
      ],
    },
  },
  {
    id: 'facebook_app_id',
    index: 'facebook_app_id',
    label: 'Facebook App ID',
    elementType: 'textArea',
    value: '',
    placeHolder: '100Xxxxxyyy',
    className: 'col-md-4 col-sm-6',
    options: {
      required: true,
      rowLength: '100',
      validation: /([^\s])/,
      errorMsg: 'Facebook app id required',
      help: [
        `How to get them?`,
        `Go to https://developers.facebook.com/`,
        `Signup an account, if you dont have one`,
        `Once logged in your APP ID will be available on the top header`,
        `Dont forget to toggle "Enforce HTTPS" to Yes`,
        `Copy & Paste here.`,
        `You're done.`,
        `Now you allow public to login via facebook login`,
      ],
    },
  },
  {
    id: 'bgSong',
    index: 'bgSong',
    label: 'Theme Background Music',
    elementType: 'textArea',
    value: '',
    placeHolder: 'https://mysong.mp3',
    className: 'col-md-4 col-sm-6',
    options: {
      required: true,
      validation: /([^\s])/,
      rowLength: '100',
      errorMsg: 'Audio file name required',
      help: [
        `Choose your theme song playable for people`,
        `If not required, leave a slash(/)`,
        `If required, Paste it from AWS gallery (copy to clipboard button), where your media files are located`,
        `Note: Supports only AWS objects. Other sources not allowed.`,
      ],
    },
  },
  {
    id: 'bgSongDefaultPlay',
    index: 'bgSongDefaultPlay',
    label: 'Theme Music Default Play',
    elementType: 'dropDown',
    value: '',
    placeHolder: 'Select',
    list: [
      { label: 'True', value: 1 },
      { label: 'False', value: 0 },
    ],
    className: 'col-md-4 col-sm-6',
    options: {
      required: true,
      validation: /([^\s])/,
      errorMsg: 'This field is required',
      help: [
        `Theme Background Music will be played or not played during start up`,
        `If required, Paste it from AWS gallery (copy to clipboard button), where your media files are located`,
        `Note: Supports only AWS objects. Other sources not allowed.`,
      ],
    },
  },
  {
    id: 'switchSongFeatureRequired',
    index: 'switchSongFeatureRequired',
    label: 'Require background song switch?',
    elementType: 'dropDown',
    value: '',
    placeHolder: 'Select',
    className: 'col-md-4 col-sm-6',
    list: [
      { label: 'Yes', value: '1' },
      { label: 'No', value: '0' },
    ],
    options: {
      required: true,
      validation: /([^\s])/,
      errorMsg: 'This field is required',
      help: [
        `You can show or hide audio control switch to users from the global menu`,
        `This feature can be enabled or disabled basesd on your selection`,
      ],
    },
  },
  {
    id: 'bgVideo',
    index: 'bgVideo',
    label: 'Theme Background Video',
    elementType: 'textArea',
    value: '',
    placeHolder: 'https://my-video.mp4',
    className: 'col-md-4 col-sm-6',
    options: {
      required: true,
      validation: /([^\s])/,
      rowLength: '100',
      errorMsg: 'Video file name required',
      help: [
        `Choose your theme video which plays in background`,
        `Dont worry.. It will be muted`,
        `Keep a small video. Check file size not exceeds 5MB`,
        `Paste it from AWS gallery (copy to clipboard button), where your media files are located`,
        `Note: Supports only AWS objects. Other sources not allowed.`,
      ],
    },
  },
  {
    id: 'bgVideoDefaultPlay',
    index: 'bgVideoDefaultPlay',
    label: 'Theme Video Default Play',
    elementType: 'dropDown',
    value: '',
    placeHolder: 'Select',
    list: [
      { label: 'True', value: 1 },
      { label: 'False', value: 0 },
    ],
    className: 'col-md-4 col-sm-6',
    options: {
      required: true,
      validation: /([^\s])/,
      errorMsg: 'This field is required',
      help: [`Theme Background Video will be played or not played on start up`],
    },
  },
  {
    id: 'switchVideoFeatureRequired',
    index: 'switchVideoFeatureRequired',
    label: 'Require background video switch?',
    elementType: 'dropDown',
    value: '',
    placeHolder: 'Select',
    className: 'col-md-4 col-sm-6',
    list: [
      { label: 'Yes', value: '1' },
      { label: 'No', value: '0' },
    ],
    options: {
      required: true,
      validation: /([^\s])/,
      errorMsg: 'This field is required',
      help: [
        `You can show or hide video control switch to users from the global menu`,
        `This feature can be enabled or disabled basesd on your selection`,
      ],
    },
  },
  {
    id: 'bannerImg',
    index: 'bannerImg',
    label: 'Logo Image',
    elementType: 'textArea',
    value: '',
    placeHolder: 'https://my-banner-img.svg',
    className: 'col-md-4 col-sm-6',
    options: {
      required: true,
      validation: /([^\s])/,
      rowLength: '100',
      errorMsg: 'Image name required',
      help: [
        `Set your logo image`,
        `PNG or SVG type is recommended`,
        `200 X 40 dimension required`,
        `Paste it from AWS gallery (copy to clipboard button), where your media files are located`,
        `This will be available in top global header`,
        `Note: Supports only AWS objects. Other sources not allowed.`,
      ],
    },
  },
  {
    id: 'logoImg',
    index: 'logoImg',
    label: 'Logo Icon',
    elementType: 'textArea',
    value: '',
    placeHolder: 'https://my-logo.svg',
    className: 'col-md-4 col-sm-6',
    options: {
      required: true,
      validation: /([^\s])/,
      rowLength: '100',
      errorMsg: 'File name required',
      help: [
        `Set your logo icon`,
        `PNG or SVG type is recommended`,
        `Paste it from AWS gallery (copy to clipboard button), where your media files are located`,
        `Note: Supports only AWS objects. Other sources not allowed.`,
      ],
    },
  },
  {
    id: 'favIconImg',
    index: 'favIconImg',
    label: 'favicon Image',
    elementType: 'textArea',
    value: '',
    placeHolder: 'https://my-favicon.icon',
    className: 'col-md-4 col-sm-6',
    options: {
      required: true,
      validation: /$/,
      rowLength: '100',
      errorMsg: 'File name required',
      help: [
        `Set your favicon. Usually it shud be your logo`,
        `32X32 or 64X64 size is sufficient`,
        `Paste it from AWS gallery (copy to clipboard button), where your media files are located`,
        `Note: Supports only AWS objects. Other sources not allowed.`,
      ],
    },
  },
  {
    id: 'webLayoutType',
    index: 'webLayoutType',
    label: 'Web Layout Type',
    elementType: 'dropDown',
    value: '',
    placeHolder: 'Select',
    className: 'col-md-4 col-sm-6',
    list: [
      { label: 'Default', value: 'default' },
      { label: 'Classic', value: 'classic' },
    ],
    options: {
      required: true,
      validation: /([^\s])/,
      errorMsg: 'This field is required',
      help: [
        `This setup is only for large displays`,
        `Default: Occupies entire width of screen`,
        `Classic: Occupiess 70% width in screen middle`,
      ],
    },
  },
  {
    id: 'webMenuType',
    index: 'webMenuType',
    label: 'Web Menu Type',
    elementType: 'dropDown',
    value: '',
    placeHolder: 'Select',
    className: 'col-md-4 col-sm-6',
    list: [
      { label: 'Top', value: 'topMenu' },
      { label: 'Left', value: 'sideMenuLeft' },
      { label: 'Right', value: 'sideMenuRight' },
    ],
    options: {
      required: true,
      validation: /([^\s])/,
      errorMsg: 'This field is required',
      help: [`Where you want to place your menu?`, `Top, Left or Right`],
    },
  },
  {
    id: 'webTheme',
    index: 'webTheme',
    label: 'Web Theme',
    elementType: 'dropDown',
    value: '',
    placeHolder: 'Select',
    className: 'col-md-4 col-sm-6',
    list: [
      { label: 'Dark', value: 'dark' },
      { label: 'Light', value: 'light' },
    ],
    options: {
      required: true,
      validation: /([^\s])/,
      errorMsg: 'This field is required',
      help: [`How does your website look on start up?`, `Dark or Light`],
    },
  },
  {
    id: 'switchThemeFeatureRequired',
    index: 'switchThemeFeatureRequired',
    label: 'Require Theme Switch?',
    elementType: 'dropDown',
    value: '',
    placeHolder: 'Select',
    className: 'col-md-4 col-sm-6',
    list: [
      { label: 'Yes', value: '1' },
      { label: 'No', value: '0' },
    ],
    options: {
      required: true,
      validation: /([^\s])/,
      errorMsg: 'This field is required',
      help: [
        `You can show or hide theme buttons to users from the global menu`,
        `This feature can be enabled or disabled basesd on your selection`,
      ],
    },
  },
  {
    id: 'webThemeColor',
    index: 'webThemeColor',
    label: 'Web Theme Color',
    elementType: 'text',
    value: '',
    placeHolder: '#000000',
    className: 'col-md-4 col-sm-6',
    options: {
      required: true,
      validation: /([^\s])/,
      errorMsg: 'A valid color is required',
      help: [
        `Your application text color`,
        `Usualy its #000000 (black)`,
        `This decides the look and feel of your application, unless you use these color variables`,
      ],
    },
  },
  {
    id: 'webThemeBackground',
    index: 'webThemeBackground',
    label: 'Web Theme Background Color',
    elementType: 'text',
    value: '',
    placeHolder: '#c2d82e',
    className: 'col-md-4 col-sm-6',
    options: {
      required: true,
      validation: /([^\s])/,
      errorMsg: 'A valid color is required',
      help: [
        `Your application back ground color`,
        `It should be a light color, say #ffffff (white)`,
        `This decides the look and feel of your application, unless you use these color variables`,
      ],
    },
  },
  {
    id: 'fileStorageType',
    index: 'fileStorageType',
    label: 'File storage',
    elementType: 'dropDown',
    sort: 0,
    value: '',
    placeHolder: 'Select',
    className: 'col-md-4 col-sm-6',
    list: [
      { label: 'Self', value: 'SELF' },
      { label: 'AWSS3', value: 'AWSS3' },
    ],
    options: {
      required: true,
      validation: /([^\s])/,
      errorMsg: 'This field is required',
      help: [
        'Where you want to store and bring your files',
        'There are 2 types - AWSS3 and Self',
        'Select your appropriate choice',
        'Note: If AWSS3 is selected, be ready with access key id and secret access key. For more details, visit',
        '<a class="btn btn-primary btn-sm" target="_blank" href="https://aws.amazon.com/s3/">https://aws.amazon.com/s3/</a>',
      ],
    },
  },
  {
    id: 'aws_s3_access_key_id',
    index: 'aws_s3_access_key_id',
    label: 'AWS S3 Access Key ID',
    elementType: 'textArea',
    value: '',
    placeHolder: 'XXXyyyZZZ',
    className: 'col-md-4 col-sm-6',
    options: {
      required: true,
      validation: /([^\s])/,
      rowLength: '100',
      errorMsg: 'Access key id is required',
      help: [
        `How to get them?`,
        `Hope you have created an AWS S3 account`,
        `Follow these steps in https://s3.console.aws.amazon.com/`,
        `You'll see this key while adding user in create user section`,
        `You need to copy, paste it in your backup during user credentials. Else you cant retrieve`,
        `This configuration is important to maintain your images and other files`,
        `Important: You should set "AdministratorAccess" in permissions (Attach existing policies directly), else the AWS gallery module wont work`,
      ],
    },
  },
  {
    id: 'aws_s3_secret_access_key',
    index: 'aws_s3_secret_access_key',
    label: 'AWS S3 Secret Access Key',
    elementType: 'textArea',
    value: '',
    placeHolder: 'XXXyyyZZZ',
    className: 'col-md-4 col-sm-6',
    options: {
      required: true,
      validation: /([^\s])/,
      rowLength: '100',
      errorMsg: 'Secret Access key is required',
      help: [`Follow the same steps described in AWS S3 Access Key ID`],
    },
  },
  {
    id: 'aws_s3_bucket',
    index: 'aws_s3_bucket',
    label: 'AWS S3 Bucket Name',
    elementType: 'text',
    value: '',
    placeHolder: 'My-S3-Bucket',
    className: 'col-md-4 col-sm-6',
    options: {
      required: true,
      validation: /([^\s])/,
      errorMsg: 'Bucket name is required',
      help: [
        `How to get them?`,
        `Hope you have created an AWS S3 account`,
        `Follow these steps in https://s3.console.aws.amazon.com/`,
        `Create bucket name in Buckets section`,
        `Once created, click the bucket name`,
        `Go to Permissions tab`,
        `Check "Block public access" is On`,
        `Goto "Bucket policy", Edit and replace the below code with your credentials`,
        `{
					"Version": "2012-10-17",
					"Statement": [
						{
							"Sid": "Statement1",
							"Effect": "Allow",
							"Principal": {
								"AWS": "arn:aws:iam::12345678:user/xxxyyyzzz"
							},
							"Action": [
								"s3:PutObject",
								"s3:PutObjectAcl",
								"s3:DeleteObject"
							],
							"Resource": "arn:aws:s3:::yourbucketname/*"
						}
					]
				}`,
        `Go to Cross-origin resource sharing (CORS)`,
        `Edit and replace the below code with your credentials`,
        `[
					{
						"AllowedHeaders": [
							"*"
						],
						"AllowedMethods": [
							"GET",
							"PUT",
							"POST",
							"DELETE"
						],
						"AllowedOrigins": [
							"https://yourwebsite.com"
						],
						"ExposeHeaders": [
							"ETag"
						]
					}
				]`,
        `You are done. Enjoy AWS S3.`,
      ],
    },
  },
  {
    id: 'aws_s3_region',
    index: 'aws_s3_region',
    label: 'AWS S3 Region Name',
    elementType: 'text',
    value: '',
    placeHolder: 'xx-south-yy',
    className: 'col-md-4 col-sm-6',
    options: {
      required: true,
      validation: /([^\s])/,
      errorMsg: 'Region name is required',
      help: [
        `How to get them?`,
        `Hope you have created an AWS S3 account`,
        `The region name that you've selected in creating bucket section`,
        `This helps to fetch files from your nearest AWS sever region`,
        `This configuration is important to maintain your images and other files`,
      ],
    },
  },
  {
    id: 'fileStorageAccessKey',
    index: 'fileStorageAccessKey',
    label: 'File storage access key',
    elementType: 'text',
    sort: 4,
    value: '',
    placeHolder: 'ABCXYZ0123',
    className: 'col-md-4 col-sm-6',
    options: {
      required: true,
      validation: /([^\s])/,
      errorMsg: 'This field is required',
      help: [
        'Set your own custom key',
        'Change this often to avoid others using your images',
      ],
    },
  },
  {
    id: 'social_media_facebook',
    index: 'social_media_facebook',
    label: 'Facebook',
    elementType: 'textArea',
    value: '',
    placeHolder: 'https://facebook.com/xyz',
    className: 'col-md-4 col-sm-6',
    options: {
      validation: /$/,
      rowLength: '100',
      errorMsg: 'Facebook profile name is required',
      help: [`Individual or company facebook profile`],
    },
  },
  {
    id: 'social_media_twitter',
    index: 'social_media_twitter',
    label: 'Twitter',
    elementType: 'textArea',
    value: '',
    placeHolder: 'https://twitter.com/xyz',
    className: 'col-md-4 col-sm-6',
    options: {
      validation: /$/,
      rowLength: '100',
      errorMsg: 'Twitter profile name is required',
      help: [`Individual or company twitter profile`],
    },
  },
  {
    id: 'social_media_linkedIn',
    index: 'social_media_linkedIn',
    label: 'LinkedIn',
    elementType: 'textArea',
    value: '',
    placeHolder: 'https://linkedIn.com/xyz',
    className: 'col-md-4 col-sm-6',
    options: {
      validation: /$/,
      rowLength: '100',
      errorMsg: 'LinkedIn profile name is required',
      help: [`Individual or company LinkedId profile`],
    },
  },
  {
    id: 'social_media_instagram',
    index: 'social_media_instagram',
    label: 'Instagram',
    elementType: 'textArea',
    value: '',
    placeHolder: 'https://instagram.com/xyz',
    className: 'col-md-4 col-sm-6',
    options: {
      validation: /$/,
      rowLength: '100',
      errorMsg: 'Instagram profile name is required',
      help: [`Individual or company Instagram profile`],
    },
  },
  {
    id: 'switchSocialMediaFeatureRequired',
    index: 'switchSocialMediaFeatureRequired',
    label: 'Require Social Media Links?',
    elementType: 'dropDown',
    value: '',
    placeHolder: 'Select',
    className: 'col-md-4 col-sm-6',
    list: [
      { label: 'Yes', value: '1' },
      { label: 'No', value: '0' },
    ],
    options: {
      required: true,
      validation: /([^\s])/,
      rowLength: '100',
      errorMsg: 'This field is required',
      help: [
        `You can show or hide social media icon links to users from the global menu`,
        `This feature can be enabled or disabled basesd on your selection`,
      ],
    },
  },
];

const wizardData = [
  {
    id: 0,
    label: 'Credentials',
    icon: 'fa fa-key',
    filterArray: ['google_login_auth_token', 'facebook_app_id'],
  },
  {
    id: 1,
    label: 'Web Defaults',
    icon: 'fa fa-globe',
    filterArray: [
      'web',
      'email',
      'bgSong',
      'bgSongDefaultPlay',
      'switchSongFeatureRequired',
      'bgVideo',
      'bgVideoDefaultPlay',
      'switchVideoFeatureRequired',
      'bannerImg',
      'logoImg',
      'favIconImg',
      'webLayoutType',
      'webMenuType',
      'webTheme',
      'switchThemeFeatureRequired',
      'webThemeColor',
      'webThemeBackground',
    ],
  },
  {
    id: 2,
    label: 'File storage',
    icon: 'fa fa-database',
    filterArray: [
      'fileStorageType',
      'aws_s3_access_key_id',
      'aws_s3_secret_access_key',
      'aws_s3_bucket',
      'aws_s3_region',
      'fileStorageAccessKey',
    ],
  },
  {
    id: 3,
    label: 'Social Media',
    icon: 'fa fa-share-square',
    filterArray: [
      'social_media_facebook',
      'social_media_twitter',
      'social_media_linkedIn',
      'social_media_instagram',
      'switchSocialMediaFeatureRequired',
    ],
  },
];

const userCreateForm = [
  {
    id: 'user_id',
    index: 'user_id',
    elementType: 'hidden',
    value: null,
    className: '',
  },
  {
    id: 'user_name',
    index: 'user_name',
    label: 'User name',
    elementType: 'text',
    value: '',
    placeHolder: 'User name',
    className: '',
    options: {
      required: true,
      validation: /^[a-zA-Z0-9 ]{4,20}$/g,
      errorMsg: 'User name required',
      help: [
        `Set unique user name.`,
        `This should not conflict other user names.`,
        `Min 4 letters`,
        `Max 20 letters`,
        `No special characters allowed`,
      ],
    },
  },
  {
    id: 'user_display_name',
    index: 'user_display_name',
    label: 'User display name',
    elementType: 'text',
    value: '',
    placeHolder: 'User display name',
    className: '',
    options: {
      required: true,
      validation: /^[a-zA-Z0-9 ]{4,20}$/g,
      errorMsg: 'Input does not match criteria',
      help: [
        `Min 4 letters`,
        `Max 20 letters`,
        `No special characters allowed`,
      ],
    },
  },
  {
    id: 'user_profile_name',
    index: 'user_profile_name',
    label: 'User profile name',
    elementType: 'text',
    value: '',
    placeHolder: 'User profile name',
    className: '',
    options: {
      required: true,
      validation: /^[a-zA-Z0-9 ]{4,50}$/g,
      errorMsg: 'Input does not match criteria',
      help: [
        `Min 4 letters`,
        `Max 50 letters`,
        `No special characters allowed`,
      ],
    },
  },
  {
    id: 'user_password',
    index: 'user_password',
    label: 'Password',
    elementType: 'text',
    value: '',
    placeHolder: 'Password',
    className: '',
    options: {
      required: true,
      validation:
        /^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[!@#$%^&*_])(?=.{8,})/,
      errorMsg: 'Password does not meet criteria',
      help: [
        `Min 8 letters long`,
        `Atleast 1 Capital letter`,
        `Atleast 1 Special (!@#$%^&*_) character`,
        `Atleast 1 Number`,
        `All the above are required`,
      ],
    },
  },
  {
    id: 'user_email',
    index: 'user_email',
    label: 'Email',
    elementType: 'text',
    value: '',
    placeHolder: 'Email',
    className: '',
    options: {
      required: true,
      validation: /^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,5})+$/,
      errorMsg: 'Enter a valid email',
      help: [`A valid email is required`, `Ex: abc@xyz.com`],
    },
  },
  {
    id: 'user_type',
    index: 'user_type',
    label: 'User Type',
    elementType: 'dropDown',
    value: '',
    placeHolder: 'Select',
    className: '',
    list: [],
    options: {
      required: true,
      validation: /([^\s])/,
      errorMsg: 'This field is required',
      help: [
        `Super-admin: Has access to setings and build in applications`,
        `Admin: Has access only to maintain and design pages (CRUD operations)`,
      ],
    },
  },
  {
    id: 'user_mobile',
    index: 'user_mobile',
    label: 'Mobile',
    elementType: 'number',
    value: '',
    placeHolder: 'Mobile number',
    className: '',
    options: {
      required: true,
      validation: /^[0-9]{10}$/,
      errorMsg: 'Enter a valid 10 digit mobile number',
      help: [`A Valid 10 digit mobile number`],
    },
  },
  {
    id: 'user_image_url',
    index: 'user_image_url',
    label: 'User image location',
    elementType: 'text',
    value: '',
    placeHolder: 'Image location',
    className: '',
    options: {
      help: [
        `User image file location from your AWS S3 bucket`,
        `Copy this from AWS gallery grid (Copy to clip board) button`,
        `This image will be shown while user logs in`,
      ],
    },
  },
];

export { configPanel, masterConfig, wizardData, userCreateForm };
