const propsMap = {
  Div: ['id', 'className'],
  Section: ['id', 'className'],
  P: ['id', 'className'],
  H1: ['id', 'className'],
  H2: ['id', 'className'],
  H3: ['id', 'className'],
  H4: ['id', 'className'],
  H5: ['id', 'className'],
  H6: ['id', 'className'],
  Blockquote: ['id', 'className'],
  Fieldset: ['id', 'className'],
  Form: ['id', 'className'],
  Ol: ['id', 'className'],
  Ul: ['id', 'className'],
  Li: ['id', 'className'],
  Table: ['id', 'className'],
  Thead: ['id', 'className'],
  Tbody: ['id', 'className'],
  Tr: ['id', 'className'],
  Th: ['id', 'className', 'colspan', 'rowspan'],
  Td: ['id', 'className', 'colspan', 'rowspan'],
  I: ['id', 'className'],
  A: ['id', 'className', 'href', 'target'],
  Span: ['id', 'className', 'title'],
  Em: ['id', 'className'],
  Abbr: ['id', 'className'],
  Address: ['id', 'className'],
  Article: ['id', 'className'],
  Aside: ['id', 'className'],
  Audio: ['id', 'className', 'src', 'autoplay', 'controls', 'loop', 'muted'],
  B: ['id', 'className'],
  Bdo: ['id', 'className'],
  Button: ['id', 'className', 'disabled'],
  Canvas: ['id', 'className'],
  Cite: ['id', 'className'],
  Code: ['id', 'className'],
  Embed: ['id', 'className'],
  Figcaption: ['id', 'className'],
  Figure: ['id', 'className'],
  Footer: ['id', 'className'],
  Hr: ['id', 'className'],
  Header: ['id', 'className'],
  Hgroup: ['id', 'className'],
  Iframe: ['id', 'className'],
  Input: [
    'id',
    'className',
    'type',
    'placeholder',
    'value',
    'autocomplete',
    'disabled',
    'readonly',
    'max',
    'min',
    'maxlength',
    'required',
  ],
  Kbd: ['id', 'className'],
  Keygen: ['id', 'className'],
  Label: ['id', 'className', 'htmlFor'],
  Legend: ['id', 'className'],
  Main: ['id', 'className'],
  Mark: ['id', 'className'],
  Nav: ['id', 'className'],
  Optgroup: ['id', 'className'],
  Option: ['id', 'className'],
  Path: ['id', 'className'],
  Picture: ['id', 'className'],
  Pre: ['id', 'className'],
  Progress: ['id', 'className'],
  Select: ['id', 'className'],
  Small: ['id', 'className'],
  Source: ['id', 'className'],
  Strong: ['id', 'className'],
  Sub: ['id', 'className'],
  Summary: ['id', 'className'],
  Sup: ['id', 'className'],
  Svg: ['id', 'className'],
  Template: ['id', 'className'],
  TextArea: ['id', 'className'],
  Tfoot: ['id', 'className'],
  Time: ['id', 'className'],
  Track: ['id', 'className'],
  U: ['id', 'className'],
  Video: ['id', 'className', 'src', 'autoplay', 'controls', 'loop', 'muted'],
  Media: [
    'id',
    'className',
    'mykey',
    'style',
    'unsignedUrl',
    'type',
    'optionalAttr',
    'alt',
    'view',
  ],
  GoogleMaps: ['mapAccessKey', 'height', 'defaultZoom', 'lat', 'lng'],
  GoogleMapsMarker: ['lat', 'lng'],
  SignedPdfView: ['src', 'scale'],
  Link: ['href'],
  Boogle: [],
  Apps: [],
  // bootstrap
  BootstrapAlert: [
    'closeLabel',
    'dismissible',
    'show',
    'transition',
    'variant',
    'bsPrefix',
  ],
  BootstrapAlertLink: ['bsPrefix'],
  BootstrapAlertHeading: ['bsPrefix'],
  BootstrapAccordion: ['activeKey', 'defaultActiveKey', 'bsPrefix'],
  BootstrapAccordionItem: [],
  BootstrapAccordionHeader: [],
  BootstrapAccordionBody: [], // here
  BootstrapAccordionCustomButton: ['id', 'className'],
  BootstrapBadge: ['id', 'className'],
  BootstrapBreadCrumb: ['id', 'className'],
  BootstrapBreadCrumbItem: ['id', 'className'],
  BootstrapButton: ['id', 'className'],
  BootstrapToggleCheckboxButtonGroup: ['id', 'className'],
  BootstrapToggleRadioButtonGroup: ['id', 'className'],
  BootstrapToggleButton: ['id', 'className'],
  BootstrapButtonToolbar: ['id', 'className'],
  BootstrapButtonGroup: ['id', 'className'],
  BootstrapCardGroup: ['id', 'className'],
  BootstrapCard: ['id', 'className'],
  BootstrapCardImg: ['id', 'className'],
  BootstrapCardImgOverlay: ['id', 'className'],
  BootstrapCardHeader: ['id', 'className'],
  BootstrapCardFooter: ['id', 'className'],
  BootstrapCardTitle: ['id', 'className'],
  BootstrapCardLink: ['id', 'className'],
  BootstrapCardbody: ['id', 'className'],
  BootstrapCardText: ['id', 'className'],
  BootstrapListGroup: ['id', 'className'],
  BootstrapListGroupItem: ['id', 'className'],
  BootstrapCarousel: ['id', 'className'],
  BootstrapCarouselItem: ['id', 'className'],
  BootstrapCarouselCaption: ['id', 'className'],
  BootstrapRow: ['id', 'className'],
  BootstrapCol: ['id', 'className'],
  BootstrapSplitButton: ['id', 'className'],
  BootstrapFigure: ['id', 'className'],
  BootstrapFigureImage: ['id', 'className'],
  BootstrapFigureCaption: ['id', 'className'],
  BootstrapImage: ['id', 'className'],
  BootstrapNav: ['id', 'className'],
  BootstrapNavLink: ['id', 'className'],
  BootstrapNavItem: ['id', 'className'],
  BootstrapNavDropdown: ['id', 'className'],
  BootstrapNavDropdownItem: ['id', 'className'],
  BootstrapContainer: ['id', 'className'],
  BootstrapNavbar: ['id', 'className'],
  BootstrapNavbarBrand: ['id', 'className'],
  BootstrapNavbarText: ['id', 'className'],
  BootstrapNavbarToggle: ['id', 'className'],
  BootstrapNavbarCollapse: ['id', 'className'],
  BootstrapNavbarOffcanvas: ['id', 'className'],
  BootstrapTable: ['id', 'className'],
  BootstrapTabContainer: ['id', 'className'],
  BootstrapTabContent: ['id', 'className'],
  BootstrapTabPane: ['id', 'className'],
  BootstrapTooltip: ['id', 'className'],
};

export { propsMap };
