const propsMap = {
  Div: ['id', 'className'],
  Section: ['id', 'className'],
  P: ['id', 'className'],
  H1: ['id', 'className'],
  H2: ['id', 'className'],
  H3: ['id', 'className'],
  H4: ['id', 'className'],
  H5: ['id', 'className'],
  H6: ['id', 'className'],
  Blockquote: ['id', 'className'],
  Fieldset: ['id', 'className'],
  Form: ['id', 'className'],
  Ol: ['id', 'className'],
  Ul: ['id', 'className'],
  Li: ['id', 'className'],
  Table: ['id', 'className'],
  Thead: ['id', 'className'],
  Tbody: ['id', 'className'],
  Tr: ['id', 'className'],
  Th: ['id', 'className', 'colspan', 'rowspan'],
  Td: ['id', 'className', 'colspan', 'rowspan'],
  I: ['id', 'className'],
  A: ['id', 'className', 'href', 'target'],
  Span: ['id', 'className', 'title'],
  Em: ['id', 'className'],
  Abbr: ['id', 'className'],
  Address: ['id', 'className'],
  Article: ['id', 'className'],
  Aside: ['id', 'className'],
  Audio: ['id', 'className', 'src', 'autoplay', 'controls', 'loop', 'muted'],
  B: ['id', 'className'],
  Bdo: ['id', 'className'],
  Button: ['id', 'className', 'disabled'],
  Canvas: ['id', 'className'],
  Cite: ['id', 'className'],
  Code: ['id', 'className'],
  Embed: ['id', 'className'],
  Figcaption: ['id', 'className'],
  Figure: ['id', 'className'],
  Footer: ['id', 'className'],
  Hr: ['id', 'className'],
  Header: ['id', 'className'],
  Hgroup: ['id', 'className'],
  Iframe: ['id', 'className'],
  Input: [
    'id',
    'className',
    'type',
    'placeholder',
    'value',
    'autocomplete',
    'disabled',
    'readonly',
    'max',
    'min',
    'maxlength',
    'required',
  ],
  Kbd: ['id', 'className'],
  Keygen: ['id', 'className'],
  Label: ['id', 'className', 'htmlFor'],
  Legend: ['id', 'className'],
  Main: ['id', 'className'],
  Mark: ['id', 'className'],
  Nav: ['id', 'className'],
  Optgroup: ['id', 'className'],
  Option: ['id', 'className'],
  Path: ['id', 'className'],
  Picture: ['id', 'className'],
  Pre: ['id', 'className'],
  Progress: ['id', 'className'],
  Select: ['id', 'className'],
  Small: ['id', 'className'],
  Source: ['id', 'className'],
  Strong: ['id', 'className'],
  Sub: ['id', 'className'],
  Summary: ['id', 'className'],
  Sup: ['id', 'className'],
  Svg: ['id', 'className'],
  Template: ['id', 'className'],
  TextArea: ['id', 'className'],
  Tfoot: ['id', 'className'],
  Time: ['id', 'className'],
  Track: ['id', 'className'],
  U: ['id', 'className'],
  Video: ['id', 'className', 'src', 'autoplay', 'controls', 'loop', 'muted'],
  Media: [
    'id',
    'className',
    'mykey',
    'style',
    'unsignedUrl',
    'type',
    'optionalAttr',
    'alt',
    'view',
  ],
  GoogleMaps: ['mapAccessKey', 'height', 'defaultZoom', 'lat', 'lng'],
  GoogleMapsMarker: ['lat', 'lng'],
  SignedPdfView: ['src', 'scale'],
  Link: ['href'],
  Boogle: [],
  Apps: [],
  // bootstrap
  BootstrapAlert: [
    'closeLabel',
    'dismissible',
    'show',
    'transition',
    'variant',
    'bsPrefix',
  ],
  BootstrapAlertLink: ['as', 'bsPrefix'],
  BootstrapAlertHeading: ['as', 'bsPrefix'],
  BootstrapAccordion: [
    'activeKey',
    'as',
    'defaultActiveKey',
    'onSelect',
    'bsPrefix',
  ],
  BootstrapAccordionItem: [],
  BootstrapAccordionHeader: [],
  BootstrapAccordionBody: [],
  BootstrapAccordionCustomButton: ['id', 'className'],
  BootstrapBadge: ['as', 'variant', 'pill', 'bsPrefix'],
  BootstrapBreadCrumb: ['as', 'label', 'className', 'listProps', 'bsPrefix'],
  BootstrapBreadCrumbItem: [
    'as',
    'active',
    'href',
    'linkAs',
    'linkProps',
    'target',
    'title',
    'bsPrefix',
  ],
  BootstrapButton: [
    'id',
    'className',
    'active',
    'as',
    'block',
    'disabled',
    'href',
    'size',
    'target',
    'type',
    'variant',
    'bsPrefix',
  ],
  BootstrapToggleCheckboxButtonGroup: ['id', 'className'],
  BootstrapToggleRadioButtonGroup: ['id', 'className'],
  BootstrapToggleButton: ['id', 'className'],
  BootstrapButtonToolbar: ['role', 'bsPrefix'],
  BootstrapButtonGroup: [
    'as',
    'role',
    'size',
    'toggle',
    'vertical',
    'bsPrefix',
  ],
  BootstrapCardGroup: ['as', 'bsPrefix'],
  BootstrapCard: ['as', 'bg', 'body', 'border', 'text', 'bsPrefix'],
  BootstrapCardImg: ['as', 'variant', 'bsPrefix'],
  BootstrapCardImgOverlay: ['as', 'bsPrefix'],
  BootstrapCardHeader: [],
  BootstrapCardFooter: [],
  BootstrapCardTitle: [],
  BootstrapCardLink: ['href'],
  BootstrapCardbody: [],
  BootstrapCardText: [],
  BootstrapListGroup: ['variant'],
  BootstrapListGroupItem: [],
  BootstrapCarousel: [
    'activeIndex',
    'as',
    'controls',
    'defaultActiveIndex',
    'fade',
    'indicators',
    'interval',
    'keyboard',
    'nextIcon',
    'nextLabel',
    'onSelect',
    'onSlid',
    'onSlide',
    'pause',
    'prevIcon',
    'prevLabel',
    'ref',
    'slide',
    'touch',
    'wrap',
    'bsPrefix',
  ],
  BootstrapCarouselItem: ['as', 'interval', 'bsPrefix'],
  BootstrapCarouselCaption: ['as', 'bsPrefix'],
  BootstrapRow: ['id', 'className', 'xs', 'sm', 'md', 'lg', 'xl', 'noGutters'],
  BootstrapCol: ['xs', 'sm', 'md', 'lg', 'xl', 'className', 'as', 'bsPrefix'],
  BootstrapSplitButton: ['id', 'className'],
  BootstrapFigure: ['as', 'bsPrefix'],
  BootstrapFigureImage: ['width', 'height', 'alt', 'src'],
  BootstrapFigureCaption: ['as', 'bsPrefix'],
  BootstrapImage: ['id', 'className'],
  BootstrapNav: [
    'activeKey',
    'as',
    'cardHeaderBsPrefix',
    'defaultActiveKey',
    'fill',
    'justify',
    'navbar',
    'navbarBsPrefix',
    'navbarScroll',
    'onKeyDown',
    'onSelect',
    'role',
    'variant',
    'bsPrefix',
  ],
  BootstrapNavLink: [
    'active',
    'as',
    'disabled',
    'eventKey',
    'href',
    'onSelect',
    'role',
    'bsPrefix',
  ],
  BootstrapNavItem: ['as', 'role', 'bsPrefix'],
  BootstrapNavDropdown: [
    'active',
    'disabled',
    'id',
    'menuRole',
    'onClick',
    'renderMenuOnMount',
    'rootCloseEvent',
    'title',
    'bsPrefix',
  ],
  BootstrapNavDropdownItem: [],
  BootstrapContainer: ['fluid', 'as', 'bsPrefix'],
  BootstrapNavbar: [
    'as',
    'bg',
    'collapseOnSelect',
    'expand',
    'expanded',
    'fixed',
    'onSelect',
    'onToggle',
    'role',
    'sticky',
    'variant',
    'bsPrefix',
  ],
  BootstrapNavbarBrand: ['as', 'href', 'bsPrefix'],
  BootstrapNavbarText: [],
  BootstrapNavbarToggle: ['as', 'children', 'label', 'onClick', 'bsPrefix'],
  BootstrapNavbarCollapse: ['bsPrefix'],
  BootstrapNavbarOffcanvas: [],
  BootstrapTable: [
    'bordered',
    'borderless',
    'hover',
    'responsive',
    'size',
    'striped',
    'variant',
    'bsPrefix',
  ],
  BootstrapTabContainer: [
    'activeKey',
    'defaultActiveKey',
    'generateChildId',
    'id',
    'mountOnEnter',
    'onSelect',
    'transition',
    'unmountOnExit',
  ],
  BootstrapTabContent: ['as', 'bsPrefix'],
  BootstrapTabPane: [
    'active',
    'aria-labelledby',
    'as',
    'eventKey',
    'id',
    'mountOnEnter',
    'onEnter',
    'onEntered',
    'onEntering',
    'onExit',
    'onExited',
    'onExiting',
    'transition',
    'unmountOnExit',
    'bsPrefix',
  ],
  BootstrapTooltip: [
    'arrowProps',
    'id',
    'placement',
    'popper',
    'show',
    'bsPrefix',
  ],
};

export { propsMap };
