const propsMap = {
  Div: [
    { key: 'id', value: 'abc123' },
    { key: 'className', value: 'm-0 p-0' },
  ],
  Section: [
    { key: 'id', value: 'abc123' },
    { key: 'className', value: 'm-0 p-0' },
  ],
  P: [
    { key: 'id', value: 'abc123' },
    { key: 'className', value: 'm-0 p-0' },
  ],
  H1: [
    { key: 'id', value: 'abc123' },
    { key: 'className', value: 'm-0 p-0' },
  ],
  H2: [
    { key: 'id', value: 'abc123' },
    { key: 'className', value: 'm-0 p-0' },
  ],
  H3: [
    { key: 'id', value: 'abc123' },
    { key: 'className', value: 'm-0 p-0' },
  ],
  H4: [
    { key: 'id', value: 'abc123' },
    { key: 'className', value: 'm-0 p-0' },
  ],
  H5: [
    { key: 'id', value: 'abc123' },
    { key: 'className', value: 'm-0 p-0' },
  ],
  H6: [
    { key: 'id', value: 'abc123' },
    { key: 'className', value: 'm-0 p-0' },
  ],
  Blockquote: [
    { key: 'id', value: 'abc123' },
    { key: 'className', value: 'm-0 p-0' },
  ],
  Fieldset: [
    { key: 'id', value: 'abc123' },
    { key: 'className', value: 'm-0 p-0' },
  ],
  Form: [
    { key: 'id', value: 'abc123' },
    { key: 'className', value: 'm-0 p-0' },
  ],
  Ol: [
    { key: 'id', value: 'abc123' },
    { key: 'className', value: 'm-0 p-0' },
  ],
  Ul: [
    { key: 'id', value: 'abc123' },
    { key: 'className', value: 'm-0 p-0' },
  ],
  Li: [
    { key: 'id', value: 'abc123' },
    { key: 'className', value: 'm-0 p-0' },
  ],
  Table: [
    { key: 'id', value: 'abc123' },
    { key: 'className', value: 'm-0 p-0' },
  ],
  Thead: [
    { key: 'id', value: 'abc123' },
    { key: 'className', value: 'm-0 p-0' },
  ],
  Tbody: [
    { key: 'id', value: 'abc123' },
    { key: 'className', value: 'm-0 p-0' },
  ],
  Tr: [
    { key: 'id', value: 'abc123' },
    { key: 'className', value: 'm-0 p-0' },
  ],
  Th: [
    { key: 'id', value: 'abc123' },
    { key: 'className', value: 'm-0 p-0' },
    { key: 'colspan', value: 5 },
    { key: 'rowspan', value: 5 },
  ],
  Td: [
    { key: 'id', value: 'abc123' },
    { key: 'className', value: 'm-0 p-0' },
    { key: 'colspan', value: 5 },
    { key: 'rowspan', value: 5 },
  ],
  I: [
    { key: 'id', value: 'abc123' },
    { key: 'className', value: 'm-0 p-0' },
  ],
  A: [
    { key: 'id', value: 'abc123' },
    { key: 'className', value: 'm-0 p-0' },
    { key: 'href', value: '/location' },
    { key: 'target', value: '_blank' },
  ],
  Span: [
    { key: 'id', value: 'abc123' },
    { key: 'title', value: 'Mr.' },
  ],
  Em: [
    { key: 'id', value: 'abc123' },
    { key: 'className', value: 'm-0 p-0' },
  ],
  Abbr: [
    { key: 'id', value: 'abc123' },
    { key: 'className', value: 'm-0 p-0' },
  ],
  Address: [
    { key: 'id', value: 'abc123' },
    { key: 'className', value: 'm-0 p-0' },
  ],
  Article: [
    { key: 'id', value: 'abc123' },
    { key: 'className', value: 'm-0 p-0' },
  ],
  Aside: [
    { key: 'id', value: 'abc123' },
    { key: 'className', value: 'm-0 p-0' },
  ],
  Audio: [
    { key: 'className', value: 'm-0 p-0' },
    { key: 'src', value: '/url' },
    { key: 'autoplay', value: 'true' },
    { key: 'controls', value: 'true' },
    { key: 'loop', value: 'true' },
    { key: 'muted', value: 'true' },
  ],
  B: [
    { key: 'id', value: 'abc123' },
    { key: 'className', value: 'm-0 p-0' },
  ],
  Bdo: [
    { key: 'id', value: 'abc123' },
    { key: 'className', value: 'm-0 p-0' },
  ],
  Button: [
    { key: 'id', value: 'abc123' },
    { key: 'className', value: 'm-0 p-0' },
    { key: 'disabled', value: 'true' },
  ],
  Canvas: [
    { key: 'id', value: 'abc123' },
    { key: 'className', value: 'm-0 p-0' },
  ],
  Cite: [
    { key: 'id', value: 'abc123' },
    { key: 'className', value: 'm-0 p-0' },
  ],
  Code: [
    { key: 'id', value: 'abc123' },
    { key: 'className', value: 'm-0 p-0' },
  ],
  Embed: [
    { key: 'id', value: 'abc123' },
    { key: 'className', value: 'm-0 p-0' },
  ],
  Figcaption: [
    { key: 'id', value: 'abc123' },
    { key: 'className', value: 'm-0 p-0' },
  ],
  Figure: [
    { key: 'id', value: 'abc123' },
    { key: 'className', value: 'm-0 p-0' },
  ],
  Footer: [
    { key: 'id', value: 'abc123' },
    { key: 'className', value: 'm-0 p-0' },
  ],
  Hr: [
    { key: 'id', value: 'abc123' },
    { key: 'className', value: 'm-0 p-0' },
  ],
  Header: [
    { key: 'id', value: 'abc123' },
    { key: 'className', value: 'm-0 p-0' },
  ],
  Hgroup: [
    { key: 'id', value: 'abc123' },
    { key: 'className', value: 'm-0 p-0' },
  ],
  Iframe: [
    { key: 'id', value: 'abc123' },
    { key: 'className', value: 'm-0 p-0' },
  ],
  Input: [
    { key: 'id', value: 'abc123' },
    { key: 'className', value: 'm-0 p-0' },
    { key: 'type', value: 'text' },
    { key: 'placeholder', value: 'Age' },
    { key: 'value', value: '22' },
    { key: 'autocomplete', value: 'off' },
    { key: 'disabled', value: 'true' },
    { key: 'readonly', value: 'true' },
    { key: 'max', value: 0 },
    { key: 'min', value: 100 },
    { key: 'maxlength', value: 2 },
    { key: 'required', value: 'true' },
  ],
  Kbd: [
    { key: 'id', value: 'abc123' },
    { key: 'className', value: 'm-0 p-0' },
  ],
  Keygen: [
    { key: 'id', value: 'abc123' },
    { key: 'className', value: 'm-0 p-0' },
  ],
  Label: [
    { key: 'id', value: 'abc123' },
    { key: 'className', value: 'm-0 p-0' },
    'htmlFor',
  ],
  Legend: [
    { key: 'id', value: 'abc123' },
    { key: 'className', value: 'm-0 p-0' },
  ],
  Main: [
    { key: 'id', value: 'abc123' },
    { key: 'className', value: 'm-0 p-0' },
  ],
  Mark: [
    { key: 'id', value: 'abc123' },
    { key: 'className', value: 'm-0 p-0' },
  ],
  Nav: [
    { key: 'id', value: 'abc123' },
    { key: 'className', value: 'm-0 p-0' },
  ],
  Optgroup: [
    { key: 'id', value: 'abc123' },
    { key: 'className', value: 'm-0 p-0' },
  ],
  Option: [
    { key: 'id', value: 'abc123' },
    { key: 'className', value: 'm-0 p-0' },
  ],
  Path: [
    { key: 'id', value: 'abc123' },
    { key: 'className', value: 'm-0 p-0' },
  ],
  Picture: [
    { key: 'id', value: 'abc123' },
    { key: 'className', value: 'm-0 p-0' },
  ],
  Pre: [
    { key: 'id', value: 'abc123' },
    { key: 'className', value: 'm-0 p-0' },
  ],
  Progress: [
    { key: 'id', value: 'abc123' },
    { key: 'className', value: 'm-0 p-0' },
  ],
  Select: [
    { key: 'id', value: 'abc123' },
    { key: 'className', value: 'm-0 p-0' },
  ],
  Small: [
    { key: 'id', value: 'abc123' },
    { key: 'className', value: 'm-0 p-0' },
  ],
  Source: [
    { key: 'id', value: 'abc123' },
    { key: 'className', value: 'm-0 p-0' },
  ],
  Strong: [
    { key: 'id', value: 'abc123' },
    { key: 'className', value: 'm-0 p-0' },
  ],
  Sub: [
    { key: 'id', value: 'abc123' },
    { key: 'className', value: 'm-0 p-0' },
  ],
  Summary: [
    { key: 'id', value: 'abc123' },
    { key: 'className', value: 'm-0 p-0' },
  ],
  Sup: [
    { key: 'id', value: 'abc123' },
    { key: 'className', value: 'm-0 p-0' },
  ],
  Svg: [
    { key: 'id', value: 'abc123' },
    { key: 'className', value: 'm-0 p-0' },
  ],
  Template: [
    { key: 'id', value: 'abc123' },
    { key: 'className', value: 'm-0 p-0' },
  ],
  TextArea: [
    { key: 'id', value: 'abc123' },
    { key: 'className', value: 'm-0 p-0' },
  ],
  Tfoot: [
    { key: 'id', value: 'abc123' },
    { key: 'className', value: 'm-0 p-0' },
  ],
  Time: [
    { key: 'id', value: 'abc123' },
    { key: 'className', value: 'm-0 p-0' },
  ],
  Track: [
    { key: 'id', value: 'abc123' },
    { key: 'className', value: 'm-0 p-0' },
  ],
  U: [
    { key: 'id', value: 'abc123' },
    { key: 'className', value: 'm-0 p-0' },
  ],
  Video: [
    { key: 'id', value: 'abc123' },
    { key: 'className', value: 'm-0 p-0' },
    { key: 'src', value: '/url' },
    { key: 'autoplay', value: 'true' },
    { key: 'controls', value: 'true' },
    { key: 'loop', value: 'true' },
    { key: 'muted', value: 'true' },
  ],
  Media: [
    { key: 'id', value: 'abc123' },
    { key: 'className', value: 'm-0 p-0' },
    { key: 'mykey', value: 'abc123' },
    { key: 'style', value: '{}' },
    { key: 'unsignedUrl', value: '/url' },
    { key: 'type', value: 'audio | image | video' },
    { key: 'optionalAttr', value: '{}' },
    { key: 'alt', value: 'alt-text' },
    { key: 'view', value: 'thumbnail' },
  ],
  GoogleMaps: [
    { key: 'mapAccessKey', value: 'abcxyz1230321' },
    { key: 'height', value: '200' },
    { key: 'defaultZoom', value: '10' },
    { key: 'lat', value: '13.05' },
    { key: 'lng', value: '80.23' },
  ],
  GoogleMapsMarker: [
    { key: 'lat', value: '13.05' },
    { key: 'lng', value: '80.23' },
  ],
  SignedPdfView: [
    { key: 'src', value: '/url' },
    { key: 'scale', value: '1.2' },
  ],
  Link: [{ key: 'href', value: '/url' }],
  Boogle: [],
  Apps: [],
  BootstrapAlert: [
    { key: 'closeLabel', value: 'Close alert' },
    { key: 'dismissible', value: 'true' },
    { key: 'show', value: 'true' },
    { key: 'transition', value: 'Fade' },
    {
      key: 'variant',
      value:
        'primary | secondary | success | danger | warning | info | dark | light',
    },
    { key: 'bsPrefix', value: 'alert' },
  ],
  BootstrapAlertLink: [
    { key: 'as', value: '<SafeAnchor>' },
    { key: 'bsPrefix', value: 'alert-link' },
  ],
  BootstrapAlertHeading: [
    { key: 'as', value: '<DivStyledAsH4>' },
    { key: 'bsPrefix', value: 'alert-heading' },
  ],
  BootstrapAccordion: [
    { key: 'activeKey', value: '1' },
    { key: 'as', value: '<CustomElement>' },
    { key: 'defaultActiveKey', value: '1' },
    { key: 'onSelect', value: 'callBack()' },
    { key: 'bsPrefix', value: 'accordion' },
  ],
  BootstrapAccordionItem: [],
  BootstrapAccordionHeader: [],
  BootstrapAccordionBody: [],
  BootstrapAccordionCustomButton: [
    { key: 'id', value: 'abc123' },
    { key: 'className', value: 'm-0 p-0' },
  ],
  BootstrapBadge: [
    { key: 'as', value: '<span>' },
    {
      key: 'variant',
      value:
        'primary | secondary | success | danger | warning | info | dark | light',
    },
    { key: 'pill', value: 'true' },
    { key: 'bsPrefix', value: 'badge' },
  ],
  BootstrapBreadCrumb: [
    { key: 'as', value: '<nav>' },
    { key: 'label', value: 'breadcrumb' },
    { key: 'className', value: 'm-0 p-0' },
    { key: 'listProps', value: '{}' },
    { key: 'bsPrefix', value: 'breadcrumb' },
  ],
  BootstrapBreadCrumbItem: [
    { key: 'as', value: '<li>' },
    { key: 'active', value: 'false' },
    { key: 'href', value: '/url' },
    { key: 'linkAs', value: '<SafeAnchor>' },
    { key: 'linkProps', value: '{}' },
    { key: 'target', value: '_blank' },
    { key: 'title', value: 'Mr.' },
    { key: 'bsPrefix', value: 'breadcrumb-item' },
  ],
  BootstrapButton: [
    { key: 'id', value: 'abc123' },
    { key: 'className', value: 'm-0 p-0' },
    { key: 'active', value: 'false' },
    { key: 'as', value: '<CustomElement>' },
    { key: 'block', value: 'true' },
    { key: 'disabled', value: 'true' },
    { key: 'href', value: '/url' },
    { key: 'size', value: 'sm | lg' },
    { key: 'target', value: '_blank' },
    { key: 'type', value: '' },
    {
      key: 'variant',
      value:
        'primary | secondary | success | danger | warning | info | dark | light',
    },
    { key: 'bsPrefix', value: 'btn' },
  ],
  BootstrapToggleCheckboxButtonGroup: [
    { key: 'id', value: 'abc123' },
    { key: 'className', value: 'm-0 p-0' },
  ],
  BootstrapToggleRadioButtonGroup: [
    { key: 'id', value: 'abc123' },
    { key: 'className', value: 'm-0 p-0' },
  ],
  BootstrapToggleButton: [
    { key: 'id', value: 'abc123' },
    { key: 'className', value: 'm-0 p-0' },
  ],
  BootstrapButtonToolbar: [
    { key: 'role', value: 'toolbar' },
    { key: 'bsPrefix', value: 'btn-toolbar' },
  ],
  BootstrapButtonGroup: [
    { key: 'as', value: '<div>' },
    { key: 'role', value: 'group' },
    { key: 'size', value: 'sm | lg' },
    { key: 'toggle', value: 'true' },
    { key: 'vertical', value: 'false' },
    { key: 'bsPrefix', value: 'btn-group' },
  ],
  BootstrapCardGroup: [
    { key: 'as', value: '<div>' },
    { key: 'bsPrefix', value: 'card-group' },
  ],
  BootstrapCard: [
    { key: 'as', value: '<div>' },
    {
      key: 'bg',
      value:
        'primary | secondary | success | danger | warning | info | dark | light',
    },
    { key: 'body', value: 'true' },
    {
      key: 'border',
      value:
        'primary | secondary | success | danger | warning | info | dark | light',
    },
    {
      key: 'text',
      value:
        'primary | secondary | success | danger | warning | info | dark | light',
    },
    { key: 'bsPrefix', value: 'card' },
  ],
  BootstrapCardImg: [
    { key: 'as', value: '<img>' },
    { key: 'variant', value: 'top | bottom' },
    { key: 'bsPrefix', value: 'card-img' },
  ],
  BootstrapCardImgOverlay: [
    { key: 'as', value: '<div>' },
    { key: 'bsPrefix', value: 'card-img-overlay' },
  ],
  BootstrapCardHeader: [],
  BootstrapCardFooter: [],
  BootstrapCardTitle: [],
  BootstrapCardLink: [{ key: 'href', value: '/url' }],
  BootstrapCardbody: [],
  BootstrapCardText: [],
  BootstrapListGroup: [
    { key: 'activeKey', value: '1' },
    { key: 'as', value: '<CustomElement>' },
    { key: 'defaultActiveKey', value: '1' },
    { key: 'horizontal', value: 'true | sm | md | lg | xl' },
    { key: 'onSelect', value: 'callBack()' },
    { key: 'variant', value: 'flush' },
    { key: 'bsPrefix', value: 'list-group' },
  ],
  BootstrapListGroupItem: [],
  BootstrapCarousel: [
    { key: 'activeIndex', value: '1' },
    { key: 'as', value: '<CustomElement>' },
    { key: 'controls', value: 'true' },
    { key: 'defaultActiveIndex', value: '1' },
    { key: 'fade', value: 'false' },
    { key: 'indicators', value: 'true' },
    { key: 'interval', value: '5000' },
    { key: 'keyboard', value: 'true' },
    { key: 'nextIcon', value: '<CustomElement>' },
    { key: 'nextLabel', value: 'Next' },
    { key: 'onSelect', value: 'callback()' },
    { key: 'onSlid', value: 'callback()' },
    { key: 'onSlide', value: 'callback()' },
    { key: 'pause', value: 'hover | false' },
    { key: 'prevIcon', value: '<CustomElement>' },
    { key: 'prevLabel', value: 'Previous' },
    { key: 'ref', value: '' },
    { key: 'slide', value: 'true' },
    { key: 'touch', value: 'true' },
    { key: 'wrap', value: 'true' },
    { key: 'bsPrefix', value: 'carousel' },
  ],
  BootstrapCarouselItem: [
    { key: 'as', value: '<div>' },
    { key: 'interval', value: '2000' },
    { key: 'bsPrefix', value: 'carousel-item' },
  ],
  BootstrapCarouselCaption: [
    { key: 'as', value: '<div>' },
    { key: 'bsPrefix', value: 'carousel-caption' },
  ],
  BootstrapRow: [
    { key: 'id', value: 'abc123' },
    { key: 'className', value: 'm-0 p-0' },
    { key: 'xs', value: '1 to 12' },
    { key: 'sm', value: '1 to 12' },
    { key: 'md', value: '1 to 12' },
    { key: 'lg', value: '1 to 12' },
    { key: 'xl', value: '1 to 12' },
    { key: 'noGutters', value: 'false' },
  ],
  BootstrapCol: [
    { key: 'xs', value: '1 to 12' },
    { key: 'sm', value: '1 to 12' },
    { key: 'md', value: '1 to 12' },
    { key: 'lg', value: '1 to 12' },
    { key: 'xl', value: '1 to 12' },
    { key: 'className', value: 'm-0 p-0' },
    { key: 'as', value: '<div>' },
    { key: 'bsPrefix', value: 'col' },
  ],
  BootstrapSplitButton: [
    { key: 'id', value: 'abc123' },
    { key: 'className', value: 'm-0 p-0' },
  ],
  BootstrapFigure: [
    { key: 'as', value: '<figure>' },
    { key: 'bsPrefix', value: 'figure' },
  ],
  BootstrapFigureImage: [
    { key: 'width', value: '150' },
    { key: 'height', value: '150' },
    { key: 'alt', value: '150X150' },
    { key: 'src', value: '/url' },
  ],
  BootstrapFigureCaption: [
    { key: 'as', value: '<figcaption>' },
    { key: 'bsPrefix', value: 'figure-caption' },
  ],
  BootstrapImage: [
    { key: 'id', value: 'abc123' },
    { key: 'className', value: 'm-0 p-0' },
  ],
  BootstrapNav: [
    { key: 'activeKey', value: '1' },
    { key: 'as', value: '<CustomElement>' },
    { key: 'cardHeaderBsPrefix', value: 'abc' },
    { key: 'defaultActiveKey', value: '1' },
    { key: 'fill', value: 'false' },
    { key: 'justify', value: 'false' },
    { key: 'navbar', value: 'false' },
    { key: 'navbarBsPrefix', value: 'abc' },
    { key: 'navbarScroll', value: 'false' },
    { key: 'onKeyDown', value: 'callBack()' },
    { key: 'onSelect', value: 'callBack()' },
    { key: 'role', value: 'aria-*' },
    { key: 'variant', value: 'tabs | pills' },
    { key: 'bsPrefix', value: 'nav' },
  ],
  BootstrapNavLink: [
    { key: 'active', value: 'true' },
    { key: 'as', value: '<a>' },
    { key: 'disabled', value: 'false' },
    { key: 'eventKey', value: 'string | number' },
    { key: 'href', value: '/url' },
    { key: 'onSelect', value: 'callBack()' },
    { key: 'role', value: 'aria-*' },
    { key: 'bsPrefix', value: 'nav-link' },
  ],
  BootstrapNavItem: [
    { key: 'as', value: '<div>' },
    { key: 'role', value: 'aria-*' },
    { key: 'bsPrefix', value: 'nav-item' },
  ],
  BootstrapNavDropdown: [
    { key: 'active', value: 'true' },
    { key: 'disabled', value: 'true' },
    { key: 'id', value: 'abc123' },
    { key: 'menuRole', value: 'aria-*' },
    { key: 'onClick', value: 'callBack()' },
    { key: 'renderMenuOnMount', value: 'false' },
    { key: 'rootCloseEvent', value: 'callBack()' },
    { key: 'title', value: 'Mr.' },
    { key: 'bsPrefix', value: 'string' },
  ],
  BootstrapNavDropdownItem: [],
  BootstrapContainer: [
    { key: 'fluid', value: 'true | sm | md | lg | xl' },
    { key: 'as', value: '<div>' },
    { key: 'bsPrefix', value: 'container' },
  ],
  BootstrapNavbar: [
    { key: 'as', value: '<CustomElement>' },
    { key: 'bg', value: 'light | dark' },
    { key: 'collapseOnSelect', value: 'false' },
    { key: 'expand', value: 'true | sm | md | lg | xl' },
    { key: 'expanded', value: 'false' },
    { key: 'fixed', value: 'top | bottom' },
    { key: 'onSelect', value: 'callBack()' },
    { key: 'onToggle', value: 'callBack()' },
    { key: 'role', value: 'aria-*' },
    { key: 'sticky', value: 'top' },
    { key: 'variant', value: 'light | dark' },
    { key: 'bsPrefix', value: 'navbar' },
  ],
  BootstrapNavbarBrand: [
    { key: 'as', value: '<CustomElement>' },
    { key: 'href', value: '/url' },
    { key: 'bsPrefix', value: 'navbar' },
  ],
  BootstrapNavbarText: [],
  BootstrapNavbarToggle: [
    { key: 'as', value: '<button>' },
    { key: 'children', value: '<CustomElement>' },
    { key: 'label', value: 'string' },
    { key: 'onClick', value: 'callBack()' },
    { key: 'bsPrefix', value: 'navbar-toggler' },
  ],
  BootstrapNavbarCollapse: [{ key: 'bsPrefix', value: 'navbar-collapse' }],
  BootstrapNavbarOffcanvas: [],
  BootstrapTable: [
    { key: 'bordered', value: 'true' },
    { key: 'borderless', value: 'false' },
    { key: 'hover', value: 'true' },
    { key: 'responsive', value: 'true' },
    { key: 'size', value: 'xs | sm | md | lg' },
    { key: 'striped', value: 'true' },
    { key: 'variant', value: 'light | dark' },
    { key: 'bsPrefix', value: 'table' },
  ],
  BootstrapTabContainer: [
    { key: 'activeKey', value: '1' },
    { key: 'defaultActiveKey', value: '1' },
    { key: 'generateChildId', value: 'callBack()' },
    { key: 'id', value: 'abc123' },
    { key: 'mountOnEnter', value: 'true' },
    { key: 'onSelect', value: 'callback()' },
    { key: 'transition', value: 'Fade' },
    { key: 'unmountOnExit', value: 'false' },
  ],
  BootstrapTabContent: [
    { key: 'as', value: '<div>' },
    { key: 'bsPrefix', value: 'tab-content' },
  ],
  BootstrapTabPane: [
    { key: 'active', value: 'false' },
    { key: 'aria-labelledby', value: 'aria-*' },
    { key: 'as', value: '<CustomElement>' },
    { key: 'eventKey', value: '1' },
    { key: 'id', value: 'abc123' },
    { key: 'mountOnEnter', value: 'false' },
    { key: 'onEnter', value: 'callback()' },
    { key: 'onEntered', value: 'callback()' },
    { key: 'onEntering', value: 'callback()' },
    { key: 'onExit', value: 'callback()' },
    { key: 'onExited', value: 'callback()' },
    { key: 'onExiting', value: 'callback()' },
    { key: 'transition', value: 'Fade' },
    { key: 'unmountOnExit', value: 'false' },
    { key: 'bsPrefix', value: 'tab-pane' },
  ],
  BootstrapTooltip: [
    { key: 'arrowProps', value: '{}' },
    { key: 'id', value: 'abc123' },
    {
      key: 'placement',
      value:
        'auto-start | auto | auto-end | top-start | top | top-end | right-start | right | right-end | bottom-end | bottom | bottom-start | left-end | left | left-start',
    },
    { key: 'popper', value: '{}' },
    { key: 'show', value: 'false' },
    { key: 'bsPrefix', value: 'tooltip' },
  ],
};

export { propsMap };
